// src/components/wc-embed-html/index.ts
export class WcEmbedHtml extends HTMLElement {
  static observedAttributes = ["src"];

  constructor() {
    super();
  }

  static register() {
    customElements.define("wc-embed-html", WcEmbedHtml);
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (name !== 'src' || newValue === oldValue) {
      return
    }
    this.#embed(newValue)
  }

  async #embed(url: string) {
    this.innerHTML = ''
    const frame = document.createElement('iframe')
    
    for (const attribute of Array.from(this.attributes)) {
      if (attribute.name === "src" || attribute.name === "class") continue
      frame.setAttribute(attribute.name, attribute.value)
    }

    frame.src = url
    frame.loading = this.getAttribute("loading") || undefined

    this.appendChild(frame)

    frame.onload = () => {
      const html = frame.contentDocument.querySelector('html')
      const body = frame.contentDocument.querySelector('body')
      body.style.margin = '0'

      frame.style.height = `${Math.ceil(html.getBoundingClientRect().height)}px`
    }
  }
}

declare module 'preact' {
  namespace JSX {
      interface IntrinsicElements {
          'wc-embed-html': WcEmbedHtmlAttributes;
      }
  }
}

interface WcEmbedHtmlAttributes extends preact.JSX.HTMLAttributes<HTMLElement> {
  src?: string;
}

// docs/components/embed-html/embed-html.tsx
import { Component, ReactNode } from "react"

export type EmbedHtmlProps = {
  src: string,
  loading?: 'lazy'
}

export default class EmbedHtml extends Component<EmbedHtmlProps, {}> {
  #hasLoaded = false

  onLoad(el: HTMLElement | null) {
    if (!el || this.#hasLoaded) {
      return
    }

    const frame = document.createElement('iframe')
    var dataUri = "data:text/plain;base64," + btoa(this.props.src);
    frame.setAttribute('src', dataUri)
    if (this.props.loading) frame.setAttribute('loading', this.props.loading)

    el.appendChild(frame)

    frame.onload = () => {
      const html = frame.contentDocument!.querySelector('html')!
      const body = frame.contentDocument!.querySelector('body')!
      body.style.margin = '0'
      frame.style.height = `${Math.ceil(html.getBoundingClientRect().height)}px`
    }

  }
  render(): ReactNode {
      return <div ref={el => this.onLoad(el)}></div>
  }
}
